# Generated by Django 4.1 on 2022-09-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.TextField(default='', max_length=300),
        ),
    ]
