# Generated by Django 4.1 on 2022-09-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_products_price_products_price_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Title',
            field=models.TextField(max_length=300),
        ),
    ]
